<a href="https://colab.research.google.com/github/jerofax/numpyguia/blob/main/introducci%C3%B3n_a_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Libreria

In [ ]:
import numpy as np

## Lista

In [ ]:
l = [0,1,2,3,4,5,6,7,8,9]
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#Array

In [ ]:
arr=np.array(l)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[1]

1

In [ ]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[2:4]

array([2, 3])

In [ ]:
arr[-3:]

array([7, 8, 9])

#Matriz

In [ ]:
M=[(0,1,2),(3,4,5),(6,7,8)]
M=np.array(M)
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
M[0,1]

1

In [ ]:
M[0,0]+M[2,2]

8

#Matriz tridimensional

In [ ]:
Matrix=[(11,22,33),(44,55,66),(77,88,99)]
Triz=[(M,Matrix)]
Triz=np.array(Triz)
Triz

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99]]]])

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99]]]])

# Ejercicio

In [ ]:
import random

In [ ]:
n=int(input())
m=[[random.randint(1,100)for i in range(n)]for j in range(n)]
m=np.array(m)
m

3


array([[44, 33, 82],
       [14, 30, 84],
       [91, 66, 90]])

# Parte 2

In [ ]:
arr.dtype

dtype('int64')

# Cambio de tipo de datos

In [ ]:
flot=np.array([1,2,3,4,5], dtype="float64")
print(flot)
print(flot.dtype)
bolean=arr.astype(np.bool_)
print(bolean)
print(bolean.dtype)
string=arr.astype(np.string_)
print(string)
print(string.dtype)

[1. 2. 3. 4. 5.]
float64
[False  True  True  True  True  True  True  True  True  True]
bool
[b'0' b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8' b'9']
|S21


# Herramientas

# Vector


In [ ]:
tamano=np.shape(arr)
print("tamaño del vector: ", tamano)

maximo=np.max(arr)
print("dato maximo del vector: ", maximo)

minimo=np.min(arr)
print("dato minimo del vector: ", minimo)

media=np.mean(arr)
print("media del vector: ", media)

desviacion=np.std(arr)
print("desviacion del vector: ", desviacion)

arr_normalizado = (arr - media)/desviacion
print("vector normalizado: ",arr_normalizado)

suma= np.sum(arr)
print("suma de datos: ", suma)

producto=np.prod(arr)
print("producto de los datos: ", producto)


array_random=np.random.randint(10,99,size=(1,5))
print(array_random)

tamaño del vector:  (10,)
dato maximo del vector:  9
dato minimo del vector:  0
media del vector:  4.5
desviacion del vector:  2.8722813232690143
vector normalizado:  [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]
suma de datos:  45
producto de los datos:  0
[[43 28 12 44 43]]


#Matriz

In [ ]:
tamano=np.shape(M)
print("tamaño de la matriz: ", tamano)

maximo=np.max(M)
print("dato maximo de la matrizr: ", maximo)

minimo=np.min(M)
print("dato minimo de la matriz: ", minimo)

media=np.mean(M)
print("media de la matriz: ", media)

desviacion=np.std(M)
print("desviacion de la matriz: ", desviacion)

arr_normalizado = (M - media)/desviacion
print("matriz normalizado: ",arr_normalizado)

suma= np.sum(M, axis=0)
print("suma de datos: ", suma)

producto=np.prod(M, axis=1)
print("producto de los datos: ", producto)


matriz_random=np.random.randint(-10,10,size=(5, 5))
print(matriz_random)

tamaño de la matriz:  (3, 3)
dato maximo de la matrizr:  8
dato minimo de la matriz:  0
media de la matriz:  4.0
desviacion de la matriz:  2.581988897471611
matriz normalizado:  [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
suma de datos:  [ 9 12 15]
producto de los datos:  [  0  60 336]
[[  5  -8   7  -4   4]
 [  8   9  -5  -4   8]
 [  1  -1  -1  -9   2]
 [ -8   3   9  -1 -10]
 [  2   1 -10  -9   2]]
